// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import java.util.List;

import javax.vecmath.Vector3d;

import ROVU_Class_Diagram.Rovu_system.Map;
import ROVU_Class_Diagram.Rovu_system.Observer;
import ROVU_Class_Diagram.Rovu_system.Robot;
import ROVU_Class_Diagram.Rovu_system.Task;

/************************************************************/
/**
 * 
 */
public class CentralStation extends Subject {

	public Map map;
	public Task[] task;
	boolean running;
	
	public CentralStation(int mapSize) {
		//super();
		map = new Map(mapSize);
	}
	
	public void start() {
		System.out.println("Central station started");
		running = true;
		pushTask(new Task(Request.sendCoordinatesWithInterval),observers); //Let the bots send their coordinates by their own counter interval for now

	}
	
	private void pushTask(Task toPush, List<Observer> ObserversToReceive) {
		setTask(toPush);
		for(Observer observer: ObserversToReceive) {
			observer.update();
		}
	}
	
	/*public void report() {
		pushTask(new Task(Request.sendCoordinates),this.observers);
	}*/
	
	
	public void reportCoordinate(int coordinate1, int coordinate2) {
		map.setGridPointStatus(GridPointStatus.COVERED, coordinate1,coordinate2);		
	}
};
