// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;
import simbad.gui.*;
import simbad.sim.*;

import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;

import simbad.sim.Box;
import simbad.sim.EnvironmentDescription;
import simbad.sim.Wall;

import javax.swing.*;


import ROVU_Class_Diagram.Rovu_system.CentralStation;
import ROVU_Class_Diagram.Rovu_system.ObstacleFactory;
import javafx.scene.control.ComboBox;
import nl.vu.cs.s2.simbadtest.ExampleRobot;

/************************************************************/
/**
 * 
 */
public class Configuration implements ActionListener{
	
	public CentralStation centralstation;
	public Environment environment;
	
	private JFrame frame;
	private JPanel panel;
	private JLabel arches;
	private JLabel boxes;
	private JLabel robots;
	private JComboBox<String> acb;
	private JComboBox<String> bcb;
	private JComboBox<String> rcb;
	private JButton start;
	
	private int nOfArches;
	private int nOfBoxes;
	private int nOfRobots;
	
	
	public void init() {
		frame = new JFrame("Starting the ROVU System");
		frame.setVisible(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	    frame.setSize(350, 300);
	    frame.setLocation(430, 100);
	    
	    panel = new JPanel();
	    panel.setLayout(new FlowLayout(FlowLayout.LEFT));
	    frame.add(panel);
	    
	    //Will be added later if possible
//	    arches = new JLabel("Pick a number of arches for in the environment");
//	    arches.setVisible(true);
//	    panel.add(arches);
//	    
//	    String[] archChoices = {"0", "1", "2"};
//	    acb = new JComboBox<String>(archChoices);
//	    acb.setSelectedItem("2");
//	    acb.setVisible(true);
//	    panel.add(acb);
	    
	    boxes = new JLabel("Pick a number of boxes for in the environment");
	    boxes.setVisible(true);
	    panel.add(boxes);
	    
	    String[] boxChoices = {"0", "1", "2", "3", "4"};
	    bcb = new JComboBox<String>(boxChoices);
	    bcb.setSelectedItem("4");
	    bcb.setVisible(true);
	    panel.add(bcb);
	    
	    robots = new JLabel("Pick a number of robots for in the environment");
	    robots.setVisible(true);
	    panel.add(robots);
	    
	    String[] numberOfRobots = {"1", "2", "3", "4"};
	    rcb = new JComboBox<String>(numberOfRobots);
	    rcb.setSelectedItem("4");
	    rcb.setVisible(true);
	    panel.add(rcb);
	    
	    start = new JButton("Start");
	    start.addActionListener(this);
	    start.setVisible(true);
	    panel.add(start);
	    
	    panel.validate();
	    panel.repaint();
	}

	@Override
	public void actionPerformed(ActionEvent e) {
//		nOfArches = acb.getSelectedIndex();
		nOfBoxes = bcb.getSelectedIndex();
		nOfRobots = rcb.getSelectedIndex() + 1;
		frame.dispose();
		
		// request antialising so that diagonal lines are not "stairy"
        System.setProperty("j3d.implicitAntialiasing", "true");
        
        environment = new Environment(nOfArches, nOfBoxes, nOfRobots);
//        Robot r = new Robot(new Vector3d(-9.25, 0, 9.25), "Robot 1");
//        environment.add(r);
        
        Simbad simframe = new Simbad(environment, false);
        simframe.update(simframe.getGraphics());
        environment.rotateForStartingPosition();

		
	}
};
