// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import ROVU_Class_Diagram.Rovu_system.Subject;

/************************************************************/
/**
 * 
 */
public abstract class Observer {
	/**
	 * 
	 */
	public Subject[] subject;

	/**
	 * 
	 */
	public void update() {
	}
};
