// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import simbad.sim.Wall;
import simbad.sim.Box;
import simbad.sim.Arch;

import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;

/************************************************************/
/**
 * 
 */
public class ObstacleFactory {
	
	public Wall getWall(Vector3d vec, int length, int heigth, Environment env) {
		return new Wall(vec, length, heigth, env);
	}
	
	public Box getBox(Vector3d vec, Vector3f vec2, Environment env) {
		return new Box(vec, vec2, env);
	}
};
