// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

/************************************************************/
/**
 * 
 */
public enum RobotDirection {
	NORTH, WEST, SOUTH, EAST
};
