// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import java.util.ArrayList;
import java.util.List;

import javax.vecmath.Vector3d;

import simbad.sim.Agent;

/************************************************************/
/**
 * 
 */
public abstract class Subject {

	protected List<Observer> observers = new ArrayList<Observer>();
	
	public void attach(Observer observer) {
		this.observers.add(observer);
	}
	public void detach(Observer observer) {
		this.observers.remove(observer);
	}
};
