// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import javax.vecmath.Vector3d;

import simbad.sim.Agent;

/************************************************************/
/**
 * 
 */
public abstract class Subject extends Agent {

	public Subject(Vector3d arg0, String arg1) {
		super(arg0, arg1);
		// TODO Auto-generated constructor stub
	}
};
