// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU_Class_Diagram.Rovu_system;

import ROVU_Class_Diagram.Rovu_system.Request;

/************************************************************/
/**
 * 
 */
public class Task {
	/**
	 * 
	 */
	public Request request;
	
	public Task(Request request){
		this.request = request;
	}
};
